### ISSUE TITLE
AFCN isn't still in cookie items 

### ISSUE THREAD

**Issue by amiramsorbi** [karim23657/AparatUploader#1]
hi [karim23657](https://github.com/karim23657),
AFCN isn't still in cookie items . im testing it with 3 browser firefox , edge & chrome but in all of them not found AFCN in cookie items .
if it's possible check again code 
regards

**Comment by karim23657** [comment]
@karim23657  , Use cookies.txt browser extention [github](https://github.com/hrdl-github/cookies-txt) , [firefox](https://addons.mozilla.org/en-US/firefox/addon/cookies-txt/) , [chrome](https://chromewebstore.google.com/detail/get-cookiestxt-locally/cclelndahbckbenkjhflpdbgdldlbecc) 

* First you should go to https://www.aparat.com/dashboard and then export cookies
